simulation:
  simulation_time: 3.156e+7    # in secs
  time_step: 8640
  #max_allowed_force: 10
  # max_velocity_diff: meassure the adapatative accuracy (tbd)
plotting: 
  plotting_time: 10
  refresh_rate: 20
  do_repeat: off
  dot_sizes:
    min: 15
    max: 75
    size_difference: 12
    exponent_factor: 0.66