simulation:
  simulation_time: 40    # in secs
  time_step: 0.01
  max_allowed_force: 10
  # max_velocity_diff: meassure the adapatative accuracy (tbd)
plotting: 
  plotting_time: 10
  refresh_rate: 20
  do_repeat: off