simulation:
  simulation_time: 20.  # in secs
  time_step: 0.01
  min_relative_time_step_reduction: 1e2 # from adaptative but needs time step
  adaptability:
    is_adaptive: True
    max_quantile: 1.1 #2.
      # As lower is the value, more steps to process
    quantile_ignored_extremes: 15
      # increase it if particles get toguether frequently
    #max_absolute_value: 1e-4 # meassure the adapatative accuracy
    #max_deviation: #900
plotting: 
  plotting_time: 10.
  refresh_rate: 20.
  do_repeat: off
  rotation:
  - 90.
  - 0.
  - 0.
  dot_sizes:
    min: 15.0
    max: 75.0
    difference: 12.0
    exponent_factor: 0.66