simulation:
  #simulation_time:   # in secs
  #time_step: 10.
  #max_allowed_force: 10.
  min_relative_time_step_reduction: 1e1 # from adaptative but needs time step
  adaptability:
    is_adaptative: True
    max_quantile: 4 #2.
    quantile_ignored_extremes: 10
      # increase it if particles get toguether frequently
    #max_absolute_value: 1e-4 # meassure the adapatative accuracy
    #max_deviation: #900
plotting: 
  plotting_time: 10.
  refresh_rate: 20.
  do_repeat: off
  dot_sizes:
    min: 15.0
    max: 75.0
    difference: 12.0
    exponent_factor: 0.66