simulation:
  simulation_time: 3.156e+7    # in secs
  time_step: 8640
  #max_allowed_force: 10
  is_adaptative: True
  max_velocity_diff: 1e-3 # meassure the adapatative accuracy
plotting: 
  plotting_time: 10
  refresh_rate: 20
  do_repeat: off
  dot_sizes:
    min: 15.0
    max: 75.0
    difference: 12.0
    exponent_factor: 0.66